FROM golang:1.12

ENV GO111MODULE=on
ENV CGO_ENABLED=0 
ENV GOOS=linux

RUN mkdir -p /go/src/gitlab.com/scalent/goxpert
ADD .     /go/src/gitlab.com/scalent/goxpert/
# COPY database/ /go/src/gitlab.com/scalent/goxpert/database
# COPY logs/     /go/src/gitlab.com/scalent/goxpert/logs
# COPY models/   /go/src/gitlab.com/scalent/goxpert/models
WORKDIR /go/src/gitlab.com/scalent/goxpert/

#RUN go mod init 
RUN go get  github.com/canthefason/go-watcher
RUN go install github.com/canthefason/go-watcher/cmd/watcher

ENTRYPOINT  watcher -run gitlab.com/scalent/goxpert/services/user/cmd  -watch gitlab.com/scalent/goxpert/services/user


